### ISSUE TITLE
Move out .inlined-pom.xml

### ISSUE THREAD

**Issue by cstamas** [maveniverse/nisse#21]

**Comment by cstamas** [comment]
@lfvjimisola so problem about this is following:
* nisse kicks in on "session begin" (maven session begins)
* but, if you invoked `mvn clean package` your session will first run `clean` goal, so IF inlined POM is put into target, then clean runs, your POM is poof, gone.
* so what should be done here? Can you handle this in gitignore, or you will not invoke mvn clean package kind of invocations, you you want something else maybe?
*

**Comment by jimisola** [comment]
I see.

We need to be able run e.g. `mvn clean package` so using target won't work.

It would be really good if a gitignore is not needed. I'm allergic to tools that clutters git repos with files (build, configuration etc).


Potential solutions:

1. remove the inline file at end of maven execution
2. use a temp file during the maven execution

**Comment by cstamas** [comment]
Fixed by https://github.com/maveniverse/nisse/pull/23

**Comment by lfvjimisola** [comment]
Does the tmp pom.xml file exist during the whole maven build or is created by nisse, Maven reloaded with tmp pom.xml  and then file removed?

Using 0.3.1 (thanks!). However, we seem to have an issue with [one plugin](https://github.com/Ekryd/sortpom).
I'm suspecting that nisse deletes the file after it's been inlined and then the file no longer exists when sortpom executes.

`mvn com.github.ekryd.sortpom:sortpom-maven-plugin:verify -Dsort.pomFile="pom.xml" -Dsort.verifyFail="Warn"`

if I change to a full path with the original poim.xml then it works, i.e.

`-Dsort.pomFile="$CI_PROJECT_DIR/tile.xml"` 

INFO] Verifying file /builds/sysdev/devops/cicd-components/java/pom.xml


```
[INFO] Building ms001 1.2.1-18-SNAPSHOT
[INFO]   from .inlined7223120837485838984.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- sortpom:4.0.0:verify (default-cli) @ ms001 ---
[INFO] Verifying file /tmp/pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
....
Caused by: org.apache.maven.plugin.MojoFailureException: Could not read pom file: /tmp/pom.xml
```

**Comment by lfvjimisola** [comment]
One more thing, does nisse set a property with the tmp inlined pom.xml so that it can be used by others during maven lifecycle? Otherwise, I can see it being useful.

**Comment by cstamas** [comment]
@lfvjimisola please open a new issue, do not "refurbish" old one.

The "inlined POM" exists during the session, so if something "bolts on" and want to run after session, it will knock out itself. Can you create some small reproducer, as I cannot understand how would anything run after Maven session is done.
