### ISSUE TITLE
Add support for dynamic versioning (and possibly Maven CI Friendly)

### ISSUE THREAD

**Issue by jimisola** [maveniverse/nisse#9]
Other langauges and build systems have something called dynamic versioning which means that the project version can be left out in the project configuration file (here: pom.xml) and instead the version is set dynamically based on tag in git repo. It the current comment does not have tag with valid semantic version then the nearest is found and the number of commits to that commit from HEAD will be build number.

Due to a limitation in Maven the current "solution" of MojoHaus Versions Maven plugin [goal](https://www.mojohaus.org/versions/versions-maven-plugin/use-dynamic-version-from-scm-mojo.html) does not work. @cstamas described it [here](https://issues.apache.org/jira/browse/MINSTALL-202) and as a the idea is to migrate the  MojoHaus Versions Plugin goal to [nisse](https://github.com/maveniverse/nisse) as core extension.

The current goal has few [optional parameters](https://www.mojohaus.org/versions/versions-maven-plugin/use-dynamic-version-from-scm-mojo.html#optional-parameters): 

* appendSnapshot: Whether the SNAPSHOT qualifier shall be apppended or not. Default: true
* defaultVersion: The default version used when SCM repository has no commit or no version tag. 
* propertyName: The name of the property that will contain the resolved version. Default: revisionUser 
* useVersion: Use this version instead of resolving from SCM tag information.

I'm currently not sure how configuration can be made for a core extension. Any input here would be appreciated.

Also, I'm not sure if there is any benefit of using ${revision} as [Maven CI Friendly](https://maven.apache.org/maven-ci-friendly.html).

**Comment by jimisola** [comment]
My plan is to hopefully start with this next week when we gave a new sprint a work and then provide a PR.

**Comment by cstamas** [comment]
Just some context: idea with Nisse is "Maven 3 CI friendly versions done right", is just a showcase with some usable extensions.

Problems with vanilla Maven CI Friendly versions:
* has limited "vocabulary" (just 3 predefined values)
* allows use of those prefefined properties in project.version
* biggest problem: **does not ensure that interpolation did happen**, hence Maven either install/deploy unusable POMs, or you need hoops and loops w/ flatten etc.

Nisse (extension) approach is:
* allows any property that **exists** (is defined and has a value)
* **inlines** detected properties into POM, hence vanilla install/deploy works, no need for hoops and loops
* introduces a simple API for property sources

Word of warning: Nisse features will most probably be absorbed into Maven 4, while Nisse remains Maven 3 extension. But be prepared for the future :smile: 

@gnodet

**Comment by jimisola** [comment]
We will jump on Maven 4 as soon as other plugins/extensions that we use have support for it. 

There seem to have been a lot of activity around CI Friendly builds last 1-2 weeks as I followed the reference you provided.
How far out is Maven 4 and do you expect Nisse features to be absorbed into the initial stable release of Maven 4?

Also, I reckon that the "dynamic versioning" goal that I contributed to MojoHaus Versions Maven plugin would still have to be implemented for Maven 4 and it would not be made available as default property sources  in core but still as an extension. Correct?

**Comment by jimisola** [comment]
@cstamas What is your suggestion regarding implementing it for Maven 3.9? Is it a waste of time and better to do it for Maven 4. I can see that gnodet is working a lot on CI Friendly for Maven 4.

**Comment by cstamas** [comment]
Nisse is for M3, and Nisse functionality is "built in" into M4 (this was the idea, need to verify it with @gnodet )

**Comment by jimisola** [comment]
Ok. So, if I write it now for M3 then it should be quite easy to migrate to M4 then. Thanks!

**Comment by lfvjimisola** [comment]
@cstamas FYI, I just found https://github.com/pascalgn/properties-maven-extension. It's not exactly what we need (resolving a correct version from git tags and commits) but similar. However, I think it's a mix of Nisse (with the properties) and the dynamic versioning part.

**Comment by jimisola** [comment]
@cstamas Sadly, it's quite cumbersome to then activate the extension on local dev machine and in pipeline since it's not possible to:

1. point out extensions.xml like we can do with e.g. settings.xml and --settings
2. can't add extensions to settings.xml
